// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/plugins": {
            "get": {
                "description": "List all plugins.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all plugins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.PluginEntry"
                            }
                        }
                    }
                }
            }
        },
        "/v1/plugins/{plugin}/dates": {
            "get": {
                "description": "List all dates (MM-DD) for a specific plugin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all dates (MM-DD) for plugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin",
                        "name": "plugin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/plugins/{plugin}/dates/{date}": {
            "get": {
                "description": "List all entries for a given date (MM-DD) and plugin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all entries for a given date (MM-DD) and plugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin",
                        "name": "plugin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Entry"
                            }
                        }
                    }
                }
            }
        },
        "/v1/plugins/{plugin}/fulldates": {
            "get": {
                "description": "List all dates (YYYY-MM-DD) for a specific plugin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all dates (YYYY-MM-DD) for plugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin",
                        "name": "plugin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/plugins/{plugin}/fulldates/{fulldate}": {
            "get": {
                "description": "List all entries for a given date (YYYY-MM-DD) and plugin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all entries for a given date (YYYY-MM-DD) and plugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin",
                        "name": "plugin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "fulldate",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Entry"
                            }
                        }
                    }
                }
            }
        },
        "/v1/plugins/{plugin}/images/{imageid}": {
            "get": {
                "description": "Get image with given identifier in plugin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Get image with given identifier in plugin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plugin",
                        "name": "plugin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Image UUID",
                        "name": "imageid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics": {
            "get": {
                "description": "List all registered topics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all topics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/dates": {
            "get": {
                "description": "List all dates for a specific topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all dates for topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/dates/{date}": {
            "get": {
                "description": "List all entries for a given date (MM-DD) and topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all entries for a given date (MM-DD) and topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (MM-DD)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Entry"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/fulldates": {
            "get": {
                "description": "List all dates (in the form YYYY-MM-DD) for a given topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all dates (YYYY-MM-DD) for topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/fulldates/{fulldate}": {
            "get": {
                "description": "List all entries for a given date (YYYY-MM-DD) and topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "List all entries for a given date (YYYY-MM-DD) and topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "fulldate",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Entry"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/images/random": {
            "get": {
                "description": "Get random image for given topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Get random image for given topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topics/{topic}/images/today-or-random": {
            "get": {
                "description": "Get Image for given topic that was created at this day x years ago. If no image is found, a random image is picked.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Get image for given topic that was created at this day x years ago or a random image.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Entry": {
            "type": "object",
            "properties": {
                "plugin": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "api.PluginEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "List general information.",
            "name": "General"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:8085",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "MindfulBytes REST API",
	Description: "This is the MindfulBytes API documentation.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
